### ISSUE TITLE
Deep tree

### ISSUE THREAD

**Issue by jaredatch** [billerickson/BE-Subpages-Widget#19]
On the site I'm working on I need to sub-menus to display deep. So not only show children of current page, but children of children etc.

What I did was change

`// Check if the subpage is in parent tree to go deeper
if ( $deep_subpages && in_array( $subpage->ID, $parents )  ) {`

to

`// Check if the subpage is in parent tree to go deeper
if ( $deep_subpages && apply_filters( 'be_subpages_widget_deep_tree', in_array( $subpage->ID, $parents ), $subpage ) ) {`

Thoughts on that? Other than not being that very performant?

I think it would be a fun idea in the future if we rewrote this to be similar to how the Yoast Breadcrumbs work. Meaning you are building a multi-dimensional array that gets output at the very end. The benefits being much easier to filter modify, and in addition to this, on output since everything is built you can them add all the helpful classes like 'has-children' etc instead if figuring it all out with jQuery (or at least that is what I'm using now). Maybe 2.0... you know, in all our spare time! 😆

**Comment by billerickson** [comment]
I actually needed to make this change recently for a project. I modified that line to:

```php
$display_subpages = $deep_subpages && in_array( $subpage->ID, $parents );
if ( apply_filters( 'be_subpages_widget_display_subpages', $display_subpages, $subpage, $depth ) ) {
```

Then you can use that filter to override it. In my specific case I needed to display all the subpages for all sections so I added 
```php
// Display all subpages in BE Subpages Widget
add_filter( 'be_subpages_widget_display_subpages', '__return_true' );
```

**Comment by jaredatch** [comment]
OK cool, good to know its not just me. Did exactly the same, just different filter name :) I'll update my filter name in the project.

👍  for adding in core.

**Comment by powerstephy** [comment]
This is exactly what I needed to do too! Thanks! I went further and added a custom css class for the grandchildren so I could style them differently. 

`echo '<div class="subpages-grandchild">';
$this->build_subpages( $deeper_pages, $parents, $deep_subpages, $depth, $nest_subpages );
echo '</div>';`

It works, but is that the "best practice" way to accomplish that? 

(Apologies if this should be another "issue" I'm not familiar with GitHub etiquette.)

**Comment by billerickson** [comment]
I think a better approach would be simply targeting the depth with CSS, like `ul > ul { }`.

If you do change the code of the plugin, I recommend setting the version number at the top to something high like 99 so that you aren't prompted for updates, which would overwrite your changes.
